services:
  pessoas:
    image: pessoas:latest
    container_name: pessoas
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - pessoas-network
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: pessoas_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: pessoas
      MYSQL_USER: pessoas
      MYSQL_PASSWORD: pessoas
      MYSQL_ROOT_PASSWORD: pessoas
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - pessoas-network

  selenium:
    image: selenium/standalone-chrome
    container_name: pessoas_selenium
    ports:
      - "7901:7900" # VNC (pra ver o browser rodando)
    networks:
      - pessoas-network
    shm_size: 2gb

networks:
  pessoas-network:

volumes:
  mariadb_data:
  vendor:

